### ISSUE TITLE
Not working on Raveos

### ISSUE THREAD

**Issue by Geniusssmit** [toncoinpool/stratum-miner#2]
hello, I used arguments 
[--bin opencl-18] [--boost 64] [--gpus 0,1,2,3,4] [--rig tonminer]
and I have that issue in console, how can I fix it?
![chrome_CwX0ZiaC9V](https://user-images.githubusercontent.com/24941285/147277623-3af77c6d-27bb-4a9c-82d3-e9ec4b197c77.jpg)

**Comment by Geniusssmit** [comment]
is it correct? I have 5 amd gpus
![image](https://user-images.githubusercontent.com/24941285/147278281-febb7e99-08ab-414c-a3ab-6efe91f6d569.png)

**Comment by sadcatjam** [comment]
Sorry for late reply. Square brackets denote optional arguments and must not be included in the actual argument string. RaveOS docs were updated with a working example
