### ISSUE TITLE
--bost not working - version 2.1.1 - [RESOLVED]

### ISSUE THREAD

**Issue by dapovoa** [toncoinpool/stratum-miner#7]
defined **--bost 0:1024**, but the output is always **-F 2048**

**Comment by sadcatjam** [comment]
The correct argument name is `--boost`, not `--bost`

**Comment by dapovoa** [comment]
yes, the correct spelling is boost.🤦‍♂️you are wright! I don't know why i wrote this way, sorry for opened an issue.
